version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "${HTTP_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      #- POSTGRES_DB=${DB_NAME}
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
  odoo_data:
    driver: local